// Update-feed generator (spec §8) — regenerates the two static feed
// documents that preview installs poll for auto-updates:
//
//   update-feeds/chrome-preview.xml    Chrome Update Manifest (gupdate)
//   update-feeds/firefox-preview.json  Firefox addon update manifest
//
// Both point at the GitHub Release assets for the given version
// (https://github.com/<repo>/releases/download/v<version>/…). The files
// are committed so the repo always reflects what's live, regenerated by
// the release workflow on every tag, and must be served at:
//
//   https://peerd.ai/updates/chrome-preview.xml
//   https://peerd.ai/updates/firefox-preview.json
//
// (the preview manifests hard-code those URLs — see
// manifests/preview.patch.json). Serve with a SHORT TTL (~5 min): Chrome
// polls every ~5h, Firefox daily-ish; a stale feed means preview users
// silently fall behind. The update-feed-monitor workflow alerts when the
// served feed disagrees with the latest GitHub Release.
//
// CLI: bun run feeds [--version=X.Y.Z] [--repo=owner/name]

import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { REPO_ROOT, MANIFESTS_DIR, readJson, readVersion, parseArgs } from './lib.ts';

const FEEDS_DIR = join(REPO_ROOT, 'update-feeds');
const DEFAULT_REPO = 'NotASithLord/peerd';

export const genUpdateFeeds = ({ version, repo }: { version: string; repo: string }): void => {
  const releaseBase = `https://github.com/${repo}/releases/download/v${version}`;
  const chromeAppId = readFileSync(join(MANIFESTS_DIR, 'preview-chrome-extension-id.txt'), 'utf8').trim();
  const previewPatch = readJson(join(MANIFESTS_DIR, 'preview.patch.json'));
  const geckoId = previewPatch.browser_specific_settings.gecko.id;
  const geckoMin = previewPatch.browser_specific_settings.gecko.strict_min_version;

  mkdirSync(FEEDS_DIR, { recursive: true });

  const chromeXml = `<?xml version="1.0" encoding="UTF-8"?>
<gupdate xmlns="http://www.google.com/update2/response" protocol="2.0">
  <app appid="${chromeAppId}">
    <updatecheck codebase="${releaseBase}/peerd-preview-chrome.crx" version="${version}"/>
  </app>
</gupdate>
`;
  writeFileSync(join(FEEDS_DIR, 'chrome-preview.xml'), chromeXml);

  const firefoxJson = {
    addons: {
      [geckoId]: {
        updates: [
          {
            version,
            update_link: `${releaseBase}/peerd-preview-firefox.xpi`,
            applications: { gecko: { strict_min_version: geckoMin } },
          },
        ],
      },
    },
  };
  writeFileSync(
    join(FEEDS_DIR, 'firefox-preview.json'),
    JSON.stringify(firefoxJson, null, 2) + '\n',
  );

  console.log(`wrote update-feeds/ for v${version} → ${releaseBase}`);
};

if (import.meta.main) {
  const args = parseArgs(process.argv.slice(2));
  genUpdateFeeds({
    version: args.version ? String(args.version) : readVersion(),
    repo: args.repo ? String(args.repo) : (process.env.GITHUB_REPOSITORY ?? DEFAULT_REPO),
  });
}
